version: "3.9"
services:
  neo4j:
    image: neo4j:5.18
    environment:
      - NEO4J_AUTH=neo4j/test
    ports: ["7474:7474","7687:7687"]
    volumes: ["neo4j-data:/data"]
  qdrant:
    image: qdrant/qdrant:v1.8.3
    ports: ["6333:6333"]
    volumes: ["qdrant-data:/qdrant/storage"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  hub:
    build: ./hub
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASS=test
      - QDRANT_URL=http://qdrant:6333
      - REDIS_URL=redis://redis:6379/0
    ports: ["8000:8000"]
    depends_on: [neo4j,qdrant,redis]
volumes:
  neo4j-data:
  qdrant-data: